export const MAIN_LIST: 'MAIN_LIST' = 'MAIN_LIST';

export const BUILD_EXTENSIONS: 'BUILD_EXTENSIONS' = 'BUILD_EXTENSIONS';
export const BUILD_SETTINGS: 'BUILD_SETTINGS' = 'BUILD_SETTINGS';
export const BUILD_SNIPPETS: 'BUILD_SNIPPETS' = 'BUILD_SNIPPETS';
export const BUILD_FULL: 'BUILD_FULL' = 'BUILD_FULL';